### ISSUE TITLE
Feature Request: Additional Land Books

### ISSUE THREAD

**Issue by PitchBright** [a3626a/EstateAgent-1.7.10#2]
Would it be possible to add Landbooks that do 2x2, 3x3, 5x5, 7x7, 9x9 Chunks… or even admin configurable areas?

They could have different coloured Ribbons on the book covers (1x1 is the current Green Ribbon Landbook)

! can make the icons for them for you if you like. Just let me know. I'll make the different coloured ribbons match the different coloured minecraft dyes & wools.

**Comment by a3626a** [comment]
I added a feature to set radius in GUI

**Comment by PitchBright** [comment]
Awesome… I'll check it out and let you know!

**Comment by PitchBright** [comment]
The new feature works AMAZING! I love it. Good job!
