### ISSUE TITLE
OP Landbook doesn't retain loaded chunks list.

### ISSUE THREAD

**Issue by PitchBright** [a3626a/EstateAgent-1.7.10#3]
I think I'm noticing that the Landbooks doesn't keep the list of loaded chunks for "Opped Player". It might be because I de-op myself from time to time to test other features of other mods, but I'm not sure. The loaded chunks are still active in the world, so that still works fine, just the missing Landbook Entries seems to be the problem.

Can you look into this, and try it yourself too and see if you can figure it out?

**Comment by a3626a** [comment]
Is this problem occurs in recent version of Estate Agent?

**Comment by PitchBright** [comment]
Version estateagent-1.0.4

I haven't had a chance to test 1.0.5 yet.

**Comment by a3626a** [comment]
That could be fixed, because I also fixed some bugs in 1.0.4, which never loading pre-exiting forced chunks list to player's client.

**Comment by PitchBright** [comment]
Okay, I'll keep an eye out for it in 1.0.5… and if it happens again, I'll report back here.

**Comment by PitchBright** [comment]
The problem appears to be resolved in 1.0.5.

Thanks a3!
